/*
 *	SWG Awakening Custom -- SuiETerminalBox.idl
 *	Copyright (C) <SWG Awakening>
 */

package server.zone.objects.player.sui.eterminalbox;

import server.zone.objects.creature.CreatureObject;
import server.zone.objects.player.sui.listbox.SuiListBox;

include server.zone.objects.tangible.terminal.eterminal.ETerminalMenuNode;
import server.zone.objects.creature.CreatureObject;

class SuiETerminalBox extends SuiListBox {
	protected transient ETerminalMenuNode rootNode;
	protected transient ETerminalMenuNode currentNode;
	
	public SuiETerminalBox(CreatureObject player, ETerminalMenuNode root) {
		super(player, SuiWindowType.E_TERMINAL_LIST, SuiListBox.HANDLETHREEBUTTON);
		
		Logger.setLoggingName("SuiETerminalBox");
		
		setPromptTitle("Enhancement Terminal");
		
		setPromptText("You can heal, get basic buffs, or remove buffs.");
		
		rootNode = root;
		
		currentNode = root;
	}
	
	public native BaseMessage generateMessage();
	
	@local
	public native ETerminalMenuNode getCurrentNode();
	
	@local
	public native void setCurrentNode(ETerminalMenuNode node);
	
	public boolean isETerminalBox() {
		return true;
	}
}
