/*
 *	SWG Awakening Custom -- Trials.h
 *	Copyright (C) <SWG Awakening>
 */

#ifndef TRIALS_H_
#define TRIALS_H_

namespace TrialName {
	enum {
		KNIGHT_TRIAL_ONE, //Kill 19 Tusken Raiders
		KNIGHT_TRIAL_TWO, //Kill 8 Ancient Bull Rancors
		KNIGHT_TRIAL_THREE, //Kill 8 Stintaril Prowlers
		KNIGHT_TRIAL_FOUR, //Kill 3 Blurrg Raptors
		KNIGHT_TRIAL_FIVE, //Kill 3 Enraged Kimogila
		KNIGHT_TRIAL_SIX, //Kill 2 Peko Peko Albatross
		KNIGHT_TRIAL_SEVEN, //Kill 2 Graul Marauders
		KNIGHT_TRIAL_EIGHT, //Kill 47 Rebel/Imp Commandos
		KNIGHT_TRIAL_NINE, //Kill 22 Rebel/Imp Generals
		KNIGHT_TRIAL_TEN, //Kill 1 Acklay
		KNIGHT_TRIAL_ELEVEN, //Kill 1 Nightsister Elder
		KNIGHT_TRIAL_TWELVE, //Kill 1 Kiin'Dray
		KNIGHT_TRIAL_THIRTEEN, //Kill 1 Giant Krayt Dragon
	};
}

namespace TrialState {
	enum {
		//Trial States
		KNIGHT_TRIAL_NOT_STARTED,
		KNIGHT_TRIAL_STARTED,
		KNIGHT_TRIAL_ONE_INPROGRESS,
		KNIGHT_TRIAL_ONE_COMPLETE,
		KNIGHT_TRIAL_TWO_INPROGRESS,
		KNIGHT_TRIAL_TWO_COMPLETE,
		KNIGHT_TRIAL_THREE_INPROGRESS,
		KNIGHT_TRIAL_THREE_COMPLETE,
		KNIGHT_TRIAL_FOUR_INPROGRESS,
		KNIGHT_TRIAL_FOUR_COMPLETE,
		KNIGHT_TRIAL_FIVE_INPROGRESS,
		KNIGHT_TRIAL_FIVE_COMPLETE,
		KNIGHT_TRIAL_SIX_INPROGRESS,
		KNIGHT_TRIAL_SIX_COMPLETE,
		KNIGHT_TRIAL_SEVEN_INPROGRESS,
		KNIGHT_TRIAL_SEVEN_COMPLETE,
		KNIGHT_TRIAL_EIGHT_INPROGRESS,
		KNIGHT_TRIAL_EIGHT_COMPLETE,
		KNIGHT_TRIAL_NINE_INPROGRESS,
		KNIGHT_TRIAL_NINE_COMPLETE,
		KNIGHT_TRIAL_TEN_INPROGRESS,
		KNIGHT_TRIAL_TEN_COMPLETE,
		KNIGHT_TRIAL_ELEVEN_INPROGRESS,
		KNIGHT_TRIAL_ELEVEN_COMPLETE,
		KNIGHT_TRIAL_TWELVE_INPROGRESS,
		KNIGHT_TRIAL_TWELVE_COMPLETE,
		KNIGHT_TRIAL_THIRTEEN_INPROGRESS,
		KNIGHT_TRIAL_THIRTEEN_COMPLETE,
	};
}

#endif
